version: 0.2
env:
  variables:
    #VERSION: "1.0"
    #IMAGE_REPO_NAME: "payment"
    AWS_ACCOUNT_ID: "877859816718"
    AWS_DEFAULT_REGION: "eu-central-1"

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel STS

  pre_build:
    commands:
      - npm install
      - npm run test:prod
      - npm run lint
  
  build:
    commands:
      - echo "Running unit-test.sh"
      - npm run build --prod
      
  post_build: 
    commands:
      - echo "Integration test complited"

